\mainmatter

\pagestyle{fancy}

# (PART) Frameworks {.unnumbered}

# Introduction {#intro}

## Background of the study

In Europe, the Neolithic is -- broadly speaking -- the long and messy transition period between mobile hunter-gatherer groups in the Palaeo- and Mesolithic, and the first city states appearing in the Bronze (Aegean) and Iron Ages [Mediterranean and Central Europe, @shennan2018]. Within this timespan of several millennia, early farmer societies evolved at different paces and in different directions, developing unique features, but also receiving indirect economic and technological impulses from the faraway Near East. Large variety in scale and content characterises the archaeologically defined culture groups of this period. In many phases and regions, single farmsteads and small hamlets were the dominant settlement feature -- for some regions and phases, like groups within the Michelsberg, Funnel Beaker and Corded Ware horizons, there is hardly any documented settlements at all. Other phases include exceptionally large settlements, probably hosting populations of several thousand inhabitants, like at Maidanetske in central Ukraine around 3.800 BCE (see \@ref(trypillia)). In some settings, like in Linear Pottery society in much of continental Europe north of the Alps towards 5.100 BCE (see \@ref(lbk)), the dead were buried in simple pit graves, either alone or in cemeteries, with only subtle distinction in treatment between individuals, in other phases some individuals were buried with tremendous amounts of precious goods like in Varna, Romania, or under colossal burial mounds like in Carnac, France, both in the mid-5th millennium [@jeunesse2017].

Seen at a very large scale -- across the continent and through the Holocene -- the development of society from small scale and relatively egalitarian towards large scale and more hierarchical seems evident [though simplistic, see @graeber2021]. When we look more closely however, this evolution is anything but linear, as both population sizes and levels of hierarchical organisation seem to fluctuate considerably, sometimes over short time spans as from the Trypillia C-I to C-II, when the so-called mega-sites are abandoned and their former inhabitants regroup into much smaller settlements during a transition of maybe only one generation [@harper2021 ; @shatilo2021; @ohlrau2020].

In many cases, the level of social hierarchy and complexity in a given Prehistoric society is very hard for researchers to evaluate, since many indicators of such structures are either lost from the archaeological record, or were never included in the first place [@perreault2019, see also Section \@ref(complexity-archaeo)]. Archaeological traces that are often interpreted as signs of social complexity and hierarchy may furthermore be deceiving. Seemingly monumental structures were in many cases built through smaller additions over longer periods of time, rather than in one colossal construction campaign [e.g. @laporte2017 for the Barnenez cairn in Brittany]. Furthermore, in many megalithic burial contexts, it may be impossible to estimate the proportion of the society that had access to such burial treatments.

In this thesis I explore the potential of a new methodological framework for evaluating the level of social hierarchy present in prehistoric societies. Fractal analysis is the general term for quantitative methods developed specifically for the study of highly irregular shapes, patterns or structures exhibiting self-similarity over large ranges of scale, so-called *fractals* [@falconer2013]. As is argued repeatedly throughout this thesis, pyramidal hierarchies constitute one type of such shapes, and fractal analysis is thus a suitable approach for finding hierarchical social structures reflected in material culture. The methods are strictly speaking not new, as they have been developed at least since the 1960s [@mandelbrot1982; @mandelbrot1967]. However, they have still only to a marginal degree been implemented in archaeological research, and thus have a high potential for use in a wide range of applications [@diachenko2018]. Inspired by recent advances within the fields of urban science and human geography [@jahanmiri2022; @lagarias2021; @themath2019; @tannier2005; @batty2005; @batty1994], with this study I wish to extend the use of fractal analysis methods also into research on prehistoric social organisation.

## Research question and objectives

The overall goal of the present study is to test and assess the utility of fractal analysis techniques as tools for studying hierarchical social organisation in prehistoric societies. Two methodological approaches are under special scrutiny: the distribution fitting approach and the image analysis approach [@brown2010; @brown2005]. These are applied to architectural data series from well-preserved and documented archaeological samples within Neolithic Linear Pottery and Trypillia contexts, as well as to synthetic data series. This thesis is thus not to be considered a culture-historic study of Linear Pottery or Trypillia society, but primarily a methodological project with two prehistoric case studies. However, results from the proposed analyses of these cases do also contribute, as side-effects, to their respective fields of research.

For the distribution fitting approach, house-size distributions within settlements are modelled following a given procedure, and the retained model (the best fit) is interpreted in terms of social generating mechanisms. In particular, it is argued here that power-law distributions reflect hierarchical structure, so that the identification of these within the studied samples may indicate the presence of some hierarchical social process which warrants further interpretation.

With the image analysis approach, the spatial layouts of archaeological and synthetic settlement plans are analysed through the calculation of fractal dimension and lacunarity -- summary statistics which serve as quantifications of irregular spatial patterns or image textures. I argue here that geometrically irregular settlement plans are indicative of relative independence between households, while settlements that develop within geometrically regular grids indicate stronger overarching social structures, with a continuous range of possibilities in-between. The goal here is to test to which extent quantitative measures like fractal dimension and lacunarity may help differentiating between varying degrees of planning in prehistoric settlements.

While both these methodological approaches are well developed and integrated to other disciplines, their usage in archaeology has so far remained anecdotal. A further overall goal of this thesis is to identify and explore possible constraints in the nature of archaeological data that may limit the applicability of fractal analysis methods within this discipline. For example, does fractal analysis of settlement plans require a data quality that would be practically unattainable in archaeological settings? But also, as it is impossible to explore all potential applications within the framework of one doctoral thesis, suggestions for future research are provided in the last chapter.

## Defining hierarchies

The term *hierarchy* is central to the present study. Though commonly used in daily speech, defining the word is not as straight-forward as one might think, so some clarification on how it is understood here might be needed. In a volume dedicated to exploring the meanings and uses of hierarchy as a study object within a range of natural and social sciences, Pumain [-@pumain2006] provides a panorama of definition nuances, but also highlighting the characteristics that are commonly found in most cases [@pumain2006]. Among these characteristics are:

-   A pyramidal organisation of elements, ordered by a very unequal size distribution of a certain quality or variable, from a few large elements on top to many small elements at the bottom

-   When seen as a system, the whole is constituted of sub-systems, which are again constituted of sub-sub-systems, and so forth. These can either be ordered into clearly distinguished levels (stratified), or in other cases be scaled in a continuum (branched or tree structure)

-   In physical, biological and social hierarchical systems, the structure is often accompanied by a flow of energy, material, information or control in one or both directions between the top and bottom levels

Hierarchies are found in humanly constructed classification and taxonomical systems, where morphological distinctions are considered more important or fundamental at the higher end of the hierarchy, while being more detailed or specific at the lower end. Many hierarchical social systems, like religious (from Greek *hieros* -- sacred, and *archê* -- government), military or corporate organisations, include strongly reinforced regulations of subordination, which in modern society has led to somewhat negative connotations to both hyper-rational and despotic rule. While one prevalent explanation for the frequency of hierarchical structures in nature and society is indeed that they "represent the best solution for many optimisation problems" [@pumain2006 p.7], that does in no way mean they need to be consciously planned. On the contrary, in most cases hierarchies seem to emerge spontaneously, often from growth processes with systems splitting into sub-systems once they reach a certain critical size limit. There is also no compulsory link between social hierarchies and despotism, as it matters little to the overall structure whether the top element is elected for a limited period or born into an inherited leading position [@delanda2006]. More detail on how hierarchical structures emerge and how they can be described as fractals, is given in Chapter \@ref(theory). A further discussion on the specifics of social hierarchies is given below in Section \@ref(social-hierarchy), and on the differences between spontaneously emergent versus consciously planned structures in Chapter \@ref(images-theory).

A possible confusion with a somewhat different meaning of the term hierarchy should however be mentioned already here. If hierarchical structures are abundant in nature in both physical (inert) and biological systems, social hierarchies on the other hand -- understood as intra-species populations of individuals organised in pyramidal hierarchical, i.e. multi-level relationships to each other -- seems to be almost exclusively found among human groups. At the same time, a different type of hierarchy is frequently described by biologists which is widespread among animals, namely *dominance hierarchies*, also known as pecking order [@strauss2022]. These structures are hierarchical in the sense that there is difference in rank between group members, and they also seem to emerge spontaneously in the animal populations where they are described. But unlike social hierarchies, these are purely *linear*, in the sense that each group member is situated in rank above one part of the group and below the rest, so that the whole group forms a rank chain in the form A \> B \> C ... n. The rank of an individual will typically decide their access to food and reproduction relative to the other members, and may be settled and resettled in a number of ways depending on the species and population under study, but typically involving some level of violence or threat and subordination in face-to-face encounters [@strauss2022].

A classic example -- perhaps most of all in popular culture -- is dominance hierarchy among wolves, led by an alpha male [e.g. @cafazzo2016; @packard2003]. Though it has been much discussed whether or not this trope model actually fits wolves [see @mech1999; @muro2011], any reported dominance hierarchies among larger groups of wolves and stray dogs are linear rather than pyramidal, even when they are illustrated as pyramidal [e.g. Fig.1 in @rodríguez2017]. Similar social organisation systems are found among a wide variety of species -- mammals, birds, fish, particularly but not only among group-hunting carnivores -- and are generally interpreted as an evolutionary mechanism [@strauss2022, with references]. Cases of branching, multi-level social hierarchies among animals are on the other hand extremely rare, but have been reported to operate among hamadryas baboons in Ethiopia, with "clan leaders" forming relays of information flow and decision making between the "one-male units" within a total population ("band") of about 200 individuals [@schreier2009]. Eusocial insects like ants and wasps provide a more well-known example of hierarchical organisation among animals [@shimoji2022], also indicating -- if it should be necessary -- that it is not a matter of intelligence or brain size, but rather of social function (e.g. building a hive or a village together) and population size above certain thresholds.

The reason to dwell upon this qualitative distinction between linear and pyramidal hierarchies, is that the prevalence of the former in nature is sometimes put forward as an argument for social hierarchies among hunter-gatherer groups in the Palaeo- and Mesolithic. To cite just one example, in their large-scope volume of the emergence of social inequality around the world over the Holocene, Flannery and Marcus [-@flannery2012, pp. 37-9, 58-60] apparently saw the need to explain away the dominance hierarchy seen among other great apes as something which among human foragers was made invisible by assigning the highest ranks to spirits and ancestors, only to re-emerge again in early city-states as kings took claim again to the alpha role, grounded on divine status. While it is a good point that there is no reason there couldn't be linear dominance hierarchies among small forager groups, and that such systems hardly can be described as egalitarian by those who live in them, @flannery2012 fail to recognise that linear (pecking order) and pyramidal (fractal) hierarchies are fundamentally different structures. And given the extreme rarity of the latter in nature, including among primates, we cannot assume that pyramidal or stratified social hierarchies have always been part of human culture, but rather that they -- much like agriculture -- at some point came to be as historical phenomena. Quite possibly, as suggested long ago by @leroi-gourhan1965, was it our capacity for language that enabled us as species to exceed the critical thresholds that would otherwise have limited our social group sizes, and organise in larger communities through a large variety of hierarchical social structures.

In recent years, there has been a large wave of research oriented to the dynamics of social inequality over deep time, often framed more or less explicitly as a search for its "origin" in time and space and its explanation [e.g. @graeber2021; @moreau2020; @kohler2018; @flannery2012; @price2010; @price1995]. Many have fallen for the temptation of conflating social inequality and hierarchy, and dealing with them as if they were the same. This, I believe has led to a number of discussions resembling semantic conundrums. Part of the problem is that words like equality or egalitarian are commonly used as the opposite of both. The difference between the concepts of social hierarchy and inequality lies in that the former relates to social and/or political organisation and the distribution of power, while the latter to economy and the distribution of wealth or income. Societies where these two are completely unrelated may be theoretically conceivable -- that is, where wealth does not entail power and *vice versa* -- but historically they have tended to go hand in hand, albeit not necessarily in a straightforward way. It is of course all too evident that money actually can buy power. However, to @graeber2021, who have advanced heavy critiques of any form of generalising narratives of increasing social inequalities throughout the Holocene, evidence of democratic institutions such as those proposed for Trypillia mega-sites, seemingly also constitutes evidence *against* social hierarchy, as if the two were intrinsically disjoint. Again, as discussed by @pumain2006 and @delanda2006, among others, the fact that a structure is hierarchical does not in itself say much about the qualitative characteristics of the top element. It can be an elected leader with a temporally limited time of office, a council of elders or of delegates from various sub-units or many other configurations that are amply described in @graeber2021. The "alpha-male" -- to return to this terribly outdated notion -- is only, if at all, one option out of many.

In sum, the related but distinct social dynamics of inequality and hierarchy should thus be studied separately and compared. Taking one variable for granted only through evidence of the other would be like assuming that the Roman Republic must have been egalitarian since it was democratic. A consequence of adopting methods specifically targeted at hierarchical structure, like fractal analysis, is that it enables us to better appreciate the variability of human social organisation, like acknowledging the existence of deeply hierarchically organised structures in economically egalitarian societies.

## Main findings

The analyses which are presented this thesis allowed for a deepened understanding of how the proposed fractal analysis methods work, and what they offer to archaeology, in particular in the study of prehistoric social hierarchy.

A review of the statistical literature related to the distribution fitting approach showed that it has deep roots and well developed theoretical foundations. The link between the statistical distribution type known as the power law is to be considered a signature of hierarchical structures, and generative mechanisms like preferential attachment are known from social and natural sciences. However, the methods related to identifying them in empirical data have undergone heavy rebuilding in recent years, a development which only to a limited degree has been picked up by archaeologists. The main application of a similar approach in archaeology, which also has existed for a long time, is the so-called rank-size rule or Zipf law approach, which despite certain merits has been shown to be gravely lacking in theoretical and methodological sophistication, which also may explain why it never has been adopted into the standard analytical tool kit of archaeologists. The recent re-branding of this approach has become known as Settlement Scaling Theory, showing considerable improvements and increased reliability in detecting hierarchically scaling settlement systems. This approach is theoretically very close to the one used in this thesis for intra-site house-size analysis, but has not been pursued further here. Current applications of Settlement Scaling are largely limited to contexts from the last two millennia, mainly in the Americas, and more systematic application on European prehistoric contexts would be welcome.

The analyses of house-size distributions provided here gave clear indications firstly that power-law distributions are to be found in Neolithic settlements, which had not been firmly demonstrated previously. This in itself is a strong argument for hierarchical scaling between households within the studied Linear Pottery and Trypillia contexts. Furthermore, power laws were demonstrated only for the largest settlements within both culture groups, i.e. settlements with more than about 80 houses in their cumulative plans. Further breakdown of the data, as well as results from tests on synthetic sets, showed that this result was not a statistical artefact from artificial data aggregation. Analysis of separate spatial and temporal sub-samples of the large Linear Pottery settlement of Vráble showed that the house sizes remained power-law distributed even when the sub-sample sizes went well within the ranges of smaller non-hierarchical settlements. Though the total sample of settlements is small, the results clearly cross-cut cultural attribution, indicating that the power-law distribution of house sizes is inherently connected to settlement size, which again implies that hierarchical scaling of households emerges with population increase beyond certain thresholds, as suggested by evolutionary psychology.

The identification of such hierarchical structures is surprising both for the Linear Pottery -- where multi-level social hierarchy is not widely accepted -- and for the Trypillia -- where current interpretations involving democratic institutions have somewhat precluded the study of hierarchy. For the Trypillia mega-sites, the identified power-law distributions went beyond the typological distinction between public and domestic buildings, and the domestic buildings which were shown to scale hierarchically, were also shown to cluster near the public buildings. These large domestic buildings have previously received little attention relative to the so-called mega-structures which are generally considered to be communal. For both cultural samples, the possibility that inhabitants of small versus large settlements lived very different lives needs to be reconsidered.

The analysis of image textures constitutes an approach which is currently on a much more experimental stage. Adapted from Mandelbrot's pioneer work in the 1970s, it has been developed and applied to contemporary urban morphology studies since the 1990s with increasingly satisfactory results. Applications to archaeological settlements have remained anecdotal and constrained to classical Mesoamerican studies. Results from analysis on synthetic data presented here indicated that much of previously published results and interpretations from archaeological settlements were highly problematic, showing signs of over-confidence to what the method could do, and to some degree limited understanding of the underlying theory. However, the same analyses on synthetic images clearly demonstrated that both fractal dimension and lacunarity (the variables calculated by the method) correlate with texture-related variables such as random noise and clustering, all other things being equal. This effect tended to be drowned by larger effects produced by methodological variables such as image size and resolution, as well as image density. It remains unclear whether these effects are fully accounted for in the cited urban studies where these methods are primarily applied. In any case, more systematic modelling on larger and carefully constructed data sets should make it possible to apply this method more efficiently on archaeological settlement plans.

The results reported here for the image analysis approach on the archaeological sample, showed moderately clear patterns. In particular, it appears that the analyses allowed for effectively differentiating between uniformly compact and loosely clustered settlements, again cross-cutting both settlement sizes and cultural attribution. While these results seem promising, it was also shown that similar results could be obtained through much simpler analytical methods, like plotting settlement size to image density on logarithmic scales. But again, it is argued that further development could strengthen the method to become an efficient tool for quantifying spatial regularity/irregularity, providing a proxy for overall planning.

## Open Science framework and data availability

Because of the experimental nature of this thesis, and its focus on quantitative methodology, it was written as an open-source Rmarkdown project using the bookdown package [@xie2018; @xie2016], with analyses done as far as possible in the R programming language [@R2023]. The data and scripts used for generating all results in this thesis can be freely consulted at the following repository:

#Repository here

Excepted are the .shp files (house outlines) which were shared to me by the GIS specialists who created them (see Section \@ref(spatial-data)). Maps and images of archaeological settlement plans were generated with QGIS software and can not be generated by the provided scripts.

## Structure of the thesis

This thesis is structured as a monograph in four parts. In the first part the overall framework of the study is exposed, with the general introduction above, the overarching theoretical framework in Chapter \@ref(theory), and the background of the study material and data in Chapter \@ref(material). Parts II and III are devoted to each their methodological approach to the material: Part II to the study of hierarchy in size distributions, and Part III to the quantification of image textures. Each of these parts consists of three chapters, the first of which -- Chapters \@ref(house-sizes-theory) and \@ref(images-theory) -- expose the theoretical and interpretative background of the applied methods and their relevance to archaeology. The following chapters -- Chapters \@ref(methods-distfit) and \@ref(images-methods) -- detail the technical specifics of the two approaches and their implementation in this study, and the last chapters within these parts -- Chapters \@ref(results-distfit) and \@ref(images-results) -- provide the actual analyses and summaries of results. In Part IV, the findings are summarised and further discussed. Chapter \@ref(disc-results) gives an attempt of interpreting the results in the context of the culture-historical setting of the European Neolithic, while Chapter \@ref(disc-methods) reviews the possibilities and limitations of the fractal analysis framework in archaeology. Concluding remarks and suggestions for further study are given in Chapter \@ref(conclusion).

Some readers might react to an apparent deviation from the academic tradition of devoting a separate chapter to research history. This is a deliberate choice, not to suggest that historiography is unimportant, but rather as a result of the fundamentally interdisciplinary scope of the study. In fact, there is very little extant history of applying fractal analysis in archaeology -- the few studies that, to my knowledge, have been done in this direction are discussed primarily in Sections \@ref(distfit-archaeo) and \@ref(image-archaeo). Fractal analysis itself holds a research history of its own (see Section \@ref(fractals)), and so does the study of Linear Pottery (Section \@ref(lbk)) and Trypillia societies (Section \@ref(trypillia)), not to mention the general study of social complexity in prehistory (mainly Section \@ref(social-hierarchy)). In short, instead of trying to shoehorn these parallel histories into a clearly delimited but rather hybrid chapter, I have opted for what I believe to be a more useful approach, namely to fit them in more seamlessly where they belong, in the various associated theory and methods chapters.

An additional note should be made here regarding the writing style of the different parts and chapters. It is my belief that a major obstacle for fractal analysis methods becoming more integrated into the standard tool kits of archaeological research, is the excessively technical nature of much of the associated literature. Archaeology as a discipline remains profoundly rooted in the Humanities, as seen in the inbuilt structure of teaching, research and funding institutions in most (at least European) countries. Fractal analysis is derived from pure mathematics, and most applications so far have been developed within the natural sciences. Archaeologists who are trained within a humanistic scholarly tradition cannot be expected to hold a skill level of mathematics more advanced than what is achieved in secondary school, and code programming is hardly taught at all within the walls of Humanities faculties. Technical details regarding the methods and analyses applied in this thesis are therefore -- as much as possible -- limited to the devoted Chapters \@ref(methods-distfit) and \@ref(images-methods), and readers who are interested in these may also refer to the online code repository for more details and reproducibility. In the rest of the thesis I have opted for a more narrative approach, in an attempt to invite a somewhat larger audience of archaeologists into the fascinating complexities of fractals.
