# Theoretical framework: Scale, Complexity and Fractals {#theory}

## Micro-macro approaches in social theory {#social-hierarchy}

### Group size, social evolution and critiques

The scalar relations between overall social structures, the individual and everything in-between is a major theme in social theory, and any discussions on the nature of social hierarchies will quickly reach in to the very core of all disciplines that deal with human societies. Here I will not attempt to do justice to such a large topic of the social sciences and humanities, but rather outline the specific questions that seem the most relevant to this thesis and that have been the most lively discussed by archaeologists and prehistorians.

The political connotations to hierarchical social structures were already mentioned in the introduction, and will be evoked repeatedly throughout this thesis. The crucial analytical distinction between political system, economic inequality and hierarchical structure is often forgotten, leading to researchers with different interests talking past each other in fruitless debates. Top-down despotic political systems are not the only possible form of hierarchy, and inversely, a search for hierarchical structure in archaeological data is not a search for top-down despotic political systems.

A recurring theme in anthropological discussions related to hierarchy -- often termed social complexity -- is its purported correlation to group size. The notion of *scalar stress* was advanced in archaeology by @johnson1982, showing to how social groups that grow to a certain size will tend to reach a limit, beyond which they can only grow by splitting (fissioning) into smaller groups, as conflict levels rise and group solidarity and integration becomes thinner [see also @alberti2014; @bandy2004; @bandy2008; @carneiro1986, @dubreuil2010, @drennan2008]. Evolutionary psychologists have proposed more causal explanations to why this happens, with the claim that the observed thresholds for maximum group sizes are largely biologically determined within species, and that subsequent fissions at higher hierarchical levels (as well as lower level groupings) tend to happen at multiples of the same threshold [@west2023; @zhou2005]. Most famously, Robin Dunbar proposed the "social brain hypothesis" in the 1990s, claiming that ideal group sizes among primate species were determined by the average size of their neocortex, with that of humans being around 150 individuals [see @dunbar2023 for a recent overview]. This idea has since been massively criticised for being too simplistic, according excessive importance to bio-genetic factors and ignoring culture [e.g. @lindenfors2021], while social media studies on very large data sets have given it more credit [e.g. @goncalves2011].

Some of the critique of what has become widely known as "Dunbar's number" seems to stem from a certain malaise related to the linking of social complexity and brain size, especially among anthropologists [e.g. @graeber2021]. Ironically, while social hierarchy often is given certain negative connotations like despotism, oppression and inequality, social complexity (which to a large extent is synonymous with hierarchy, see below) is often given a positive connotation in the sense that it is indicative of high intelligence. Such connotations are indicative of the common confusion of the terms complex and complicated. A central tenet to complexity theory is that complex phenomena, like social hierarchies, are generally not consciously planned -- they *emerge*, through repeated interactions between smaller components who obey more or less simple rules. In other words, claiming that social complexity or hierarchy emerges in large human populations, and therefore generally only from late in prehistory and onwards [e.g @ross2017; @smith2011], is not to say that these complex societies are in any way better or smarter than less complex (often forager) societies -- they are simply different. Anthropologists who deal with comparative big history routinely express the need to point out that foragers also can be highly complex [@graeber2021; @testart2012], which is of course true in many ways, but somewhat beside the point when regarding hierarchical organisation in particular. There has never been such a thing as forager emperors [though @graeber2021 do discuss some apparent exceptions].

As a small side note, some specific types of social complexity are particularly relevant for the study of forager societies. One is the phenomenon of nested hierarchies, a trait probably common to all human societies, where any single person belongs to a variety of social groups of different scales, which are made relevant in different social settings. A person can belong to a family, an extended family, a village community, an ethnic minority, a nation state, even have a continental or human identity and many other identities, at the same time. The total of all these identities form a nested hierarchy, and is indeed fractal -- there are a few large ones and many small ones -- but it is not the same as a hierarchically organised society. Nested social hierarchies among foragers is an interesting topic [@hamilton2007; @whitridge2016], which is in no way in contradiction to the general framework of this thesis. Another term which has been much debated for much the same reasons, is that of *complex hunter-gatherers* [@arnold1996], often claimed to invalidate general narratives of increasing complexity over the Holocene and its link to agriculture. These are societies now known from many parts of the world, but originally associated with North-West Coast Native American groups known for their sedentism, complex art forms, extensive food storage and competitive feasting organised by clan or house leaders (see below). To which extent they constitute exceptions of or confirmations to rules of how foragers are organised is a different debate, but it should in any case be kept in mind that they are often associated with specific eco-zones with abundant marine resources which allows them to sustain relatively large and dense populations.

-   Temporal dynamics of social hierarchies: cyclicity [@peters2017], sawtooth waves [@scheidel2017], punctuated equilibrium [@gould2007]. Transitions villages to urban: @birch2014

<!-- -->

-   Tools for classifying societies, or evolutionary model? Discussion of @johnson1987, @testart2005, @service1971, @earle1997.

    -   Lineage and Chiefdom societies @earle2002, @sahlins2020
    -   Big Men, Roscoe in @kienlin2012 ?

An additional category of social structure, which has had a certain success in archaeology, was described by Claude Lévi-Strauss as *house societies* [@lévi-strauss1982]. Here a house is a social unit, often centred around a material estate but also involving titles, heirlooms, land ownership, rights to hunting grounds etc. and where membership is not determined from genealogy in a systematic manner, as is the case with more regularly structured lineage or clan societies. House membership may be gained through more competitive social action, privileging those that possess the resources to engage in activities such as gift exchange and *potlatch*-style feasting. This opens up for more complex configurations, and house membership will often entail a certain level of prestige. Inheritance may furthermore follow (male) descent or (female) affinity -- that is from grand-father to grand-son via mother -- in a pragmatic way depending on which option is in the best interest of the house, as long as it can be justified in more or less precise kinship-related terms. A segment of society of varying size will not afford to partake in this competition, and as a result, house societies can be viewed as being in a somewhat unstable transition state between lineage and class societies. Lévi-Strauss originally pinned the term on Kwakiutl society in the American north-west coast (as described by Franz Boas), but argued for its generality by associating it with the feudal system of medieval Europe. The concept has since been applied to a wide range of cases from ethnography (especially in the South-East Asian and Pacific regions), as well as to prehistoric contexts **insert examples**, reflecting a relevance that extends far beyond European feudalism. Ian @kuijt2018 recently provided an interpretation of Neolithic Çatalöyük where he proposed that

Refs. house societies [@joyce2000; @beck2007; @kuijt2018; @lévi-strauss1982].

-   

<!-- -->

-   Anti-evolution critique in @yoffee1993, @yoffee2005, @pauketat2007, @fontijn2013, @kienlin2012, @lund2022, @furholt2020 Review in @dubreuil2010, @ragan2017. Anarchistic critique/heterarchy: @crumley1995, @haude2019, @graeber2021, @angelbeck2022
-   Paleaeolithic social inequality: e.g. in @graeber2021. Contra: @honoré2022, @testart2012, @testart1982
-   I need to address gender inequality somewhere, mainly to say that this thesis is not about gender inequality. Start from @gaydarska2023, and cite A. Augereau for the LBK.
-   Bottom line here: archaeologists should have much to gain in analytically separating social hierarchy and social inequality. While the two are often seen to go hand in hand, they do not necessarily do so. Hierarchical structure is a response, often unplanned or emergent, to scale-related stresses -- i.e. it fills a functional need in large societies. How a hierarchy is implemented socially however is a matter of considerable variation. At least one crucial variable is the spectrum between democratic and autocratic extremes. Archaeologists have apparently been speaking past each other for decades (formulate precise argument referring to @graeber2021 and @flannery2012). In this thesis I argue that hierarchical structure must be shown archaeologically through different traces in material culture than social inequality as well as type of hierarchical organisation.
-   False binary debate: everything is structural and following natural laws vs. everything is historically contingent. Both are true, that is why the debate never progresses. Arguments often reduce to what the author is interested in/finds the most important. Side note, dynamical systems theory is a good candidate for conciliating these perfectly. Evolution and punctuated equilibrium -- changes (e.g. speciations) are power-law distributed in time and scale, like earthquakes. Hard to prove in palaeontology (but does it matter? It is heavy-tailed in any case, ref clauset, machin), but that could be a task for archaeology. Continue this discussion in Chapter \@ref(disc-methods).

### Other approaches: structuralism, structuration, assemblages

-   Lévi-Strauss and Structuralism

-   Braudel and World Systems

-   Giddens and Structuration Theory

-   Delanda and Assemblage Theory

For social hierarchies, he refers to Weber's classification of legitimation strategies, as being founded on sacred tradition, personal charisma or rational bureaucracy [see also @graeber2021, pp.]. Delanda furthermore places Bourdieu's concept of *habitus* on the mid-range between micro and macro processes, as an explanation of social action that is not entirely individual dependent, but not emergent properties of society-as-a-whole either.

-   Latour and Actor-Network Theory

What these approaches all have in common, is that they are entirely qualitative (**check**).

-   That's not a problem in itself.

-   Quant approach is both possible for the stated purpose, and desirable for reasons of comparative analysis.

-   Data deluge (refer to chap. on geomagn data). The goal here is to establish a quantitative framework for studying social complexity and hierarchy in archaeological/prehistoric settings. Further articulating fractal analysis with existing social theoretical approaches is not the primary goal here, as it could constitute a separate research project. In the present thesis, bla bla.

## Complexity Theory / Dynamical Systems Theory

Lit. use @daems2021, @baden2016, @ross2017, @smith2011 and @bentley2008.

For Dynamical Systems, use @devaney2020, but don't go into detail.

Describe complexity, dynamical systems, chaos, feedback loops, criticality, emergence. Scale @west2017 NA

Social complexity is more than social hierarchy, and all societies -- whether they are classified as simple or complex within a social evolutionary framework -- can arguably be studied as complex systems, since they always consist of various sub-systems and populations of individuals acting and interacting in a variety of ways [@daems2021, p. 6]. The sense of social complexity that is traditionally understood in archaeology, derived from social evolution theory, is somewhat narrower and relates more to the specific characteristics of organisational scale (i.e. hierarchy) than to complexity per se. Studying the scale of social organisation from a complex systems perspective rather than from a social evolutionist one holds several advantages:

1.  The switch from discrete evolutionary stages to continuous spectra allows for more nuanced evaluation of the society in question, avoiding false binaries like simple-complex

2.  The complex systems approach arguably has a stronger explanatory power than the more classificatory social evolution schemes

3.  Complexity theory offers a better alternative for ethical reasons, as it avoids the underlying colonial and eurocentric connotations associated with classifying societies into simple and complex

As a further elaboration on the latter point, an analysis of a society from a complexity theoretical viewpoint is not a matter of establishing whether or not the society can be characterised as a complex system. When the scale of social organisation is the object of study -- as in the present thesis -- the word hierarchy is both more accurate and, if not neutral, at least more balanced than social complexity, since it is not obvious whether or not it is a good thing for a society to be characterised as hierarchical. The study of the dynamics of social hierarchy over time is thus not a story of progress, as the 19th century studies of social evolution too often were.

[\@hamilton2007].

Mention the most common applications in archaeology, as discussed in @daems2021, p. 13: network science, settlement scaling, cultural evolution and agent-based modelling.

### Fractals and Fractal Analysis {#fractals}

Lit. use @mandelbrot2021, @falconer2013 (general), also @brown2010, @brown2005 and @diachenko2018 (for archaeology)

The term *fractal* was pinned by the French-American mathematician Benoît Mandelbrot (1924-2010), from the latin word *fractus* meaning broken or irregular, to describe patterns that because of their apparent limitless complexity defied concise description within the framework of Euclidean geometry [@falconer2013, pp. 116-20]. Such patterns -- both theoretical and empirical -- had been described and analysed by mathematicians and researchers within other disciplines since the end of the 19th century, but were mostly regarded as curiosities and exceptions, and Mandelbrot was the first to link all these previous studies within a unified theoretical framework [@mandelbrot1975; @mandelbrot2021].

In one influential paper, drawing on previous work by mathematician Lewis Fry Richardson, @mandelbrot1967 argued that a rugged linear feature like a coastline cannot be fully described through traditional geometry with a set of line segments, since this would result in a curve of infinite complexity. More importantly, he showed that the traditional measure of lines -- the length -- will inevitably depend on the scale of observation when applied to a coastline. If measured in kilometres, a coastline will always appear shorter in total length, than if it is measured in metres, since smaller bays and inlets can then also be accounted for. But this phenomenon continues seemingly without limit, since the same coastline measured in centimetres will appear much longer, and in millimetres far longer again, and so on. Length as a measure of rugged linear features thus seems inadequate, which may become a problem in practical settings when comparing coastlines between countries that operate with different measurement units and procedures. The same problem occurs when describing irregular patterns in the plane (like island or continent outlines) with area or in three-dimensional space (like clouds or galaxies) with volume. As a solution, Mandelbrot proposed the use of the *fractal dimension* as a descriptive tool for characterising such patterns.

Fractals as hierarchy

Self-similarity and scale invariance

Processes/mechanisms that produce fractals:

-   Cascading bifurcations and confluences (splitting or merging - tree structure/arborescence/branching, and relation to size. Terminology borrowed from biology and fluid dynamics (including turbulence/turbulent flow)

The role of randomness - tidy and messy fractals (romanesco broccolis are not more fractal than regular broccolis, only more regular. Also: a system may be both random and deterministic, often only depending on scale of observation (chaos).

The relationship with (self-organised) criticality and chaos: deterministic *and* unpredictable

Fractals embedded in

-   Space (hence "fractal geometry"): geomorphology, plants, ocean and wind currents, galaxies, also human constructed features (see Chapter xx for details)

-   Time series: earthquakes, finance (not applied in this study, though should be done later)

-   Networks/abstract: hierarchical organisations, income distributions, word counts, 1/f or pink noise, www. @barabási1999 etc. (see Chapter xxx for details). Fractal social networks: @west2023.

-   Pure mathematics: Julia and Mandelbrot sets, strange attractors (don't go into details!)

No, not everything is fractal: e.g. Central Limit Theorem

Fractal analysis for studying irregular phenomena (methods described in more detail Chapters xxx), and thus as a tool for quantitative empirical research.

-   Fractal dimension (explain without math here, with math in chapter 7, box-counting in chapter 8)

-   Lacunarity (same)

END chapter.
