# Material and data: social complexity in the European Neolithic {#material}

## Studying social hierarchy in archaeology and prehistory. {#complexity-archaeo}

Grave goods

Example of Varna: Lichardus (1991; also Gimbutas), as discussed in @kadrow2013, proposed that the social inequality observed at Varna in the mid-5th millennium, was already then adopted from pastoral North Pontic steppe cultures (*check this and delete if unsure*); cf. @chapman2006 -- three social levels interpreted from grave goods, but not clear if these are really discrete or constructed on a continuum. The term *fractal* is here used purely as a metaphor for complex personhood structures, rather in opposition to the described social hierarchy. Biehl and Marciniak in Diehl 2000: no hierarchy in Varna. Response by Hayden 200?

Burial monuments

Architecture @rathje1982 -- social stratification (qualitatively) through architecture and burials (and life expectancy). Short but to-the-point article.

The denominator problem

The use of ethnography

Other approaches (osteological, isotopes, craft specialisation **refs**)

This project: house-size distributions and settlement layouts (details in subsequent chapters), just very short argumentation.

Comparative approach: Neolithic technology (not bronze axes), wood and wattle-and-daub architecture, (near) complete settlement plans/extensive documentation: Trypillia and Linear Pottery

For this project I opted for the use of houses and built environments as proxy for social hierarchy. In this way I hope to largely avoid the denominator problem associated with burials. While it is true that for many archaeological culture groups in late prehistory habitats are poorly preserved and hard to discover, leaving us still with a limited understanding of them (the case in many Michelsberg, Corded Ware and Bell Beaker groups, only to mention a few **check**), in groups where habitats are well preserved, there is little reason to suspect that the available record would not cover the whole range of social statuses if these societies were hierarchical. Unlike burials, every individual in a sedentary society -- with few exceptions like homeless persons in more recent urban contexts -- will normally have at least one fixed place to stay overnight, and these homes will in most cases be constructed within the same fundamental framework of techniques and building materials, depending more on culture specific traditions and environmental factors than on social status (\#**citation?**). As an example, in a society where mudbrick is the main building material, like in the Neolithic Near East and Anatolia, nearly all constructions are made in mudbrick, regardless of the social status of the inhabitants. In continental Europe north of the Alps, wattle-and-daub construction was the almost exclusive building technique for any architectural feature from the early Neolithic until the Roman conquest, and well into the Middle Ages north of the *limes*. One can of course enumerate exceptions, but more importantly houses are in any stratified society also a marker of social status, which can be exhibited in a range of ways, from decorations, use of more precious raw materials as well as size. That is precisely the reason for using houses as a proxy for social status and hierarchy in archaeological settings. But the point here is that there should be little taphonomic differentiation between groups of high and low status within a given archaeological context, at least in prehistory, and at least not as much as can be expected for burials, meaning that we can expect to find samples of houses that are representative of the social structure of the archaeological culture in question. On sites where there is taphonomical loss of architectural structures, as long as the overall building tradition is homogeneous, there is no reason this loss should affect one segment of the society more or less than others.

Some caveats do remain, however, for the use of houses as proxy of social status. Firstly, there may be a documentation bias favouring larger houses, since they may be easier to discover both during excavation and in remote-sensing surveys (\#**citation?**). In samples from originally very skewed house-size distributions, there may also be a further taphonomic bias towards large houses, since smaller houses -- being far more numerous -- are statistically in greater risk of being affected by post-depositional disturbances. Both of these biases are hard to evaluate empirically, though computer modelling could potentially give indications of their importance. This, however, is not within the scope of the present study.

A second, and maybe more important issue, is that of the contemporaneity of houses. When the goal is to investigate the social structure of a settlement as reflected in its architecture -- be it through the size distribution of buildings or their spatial layout -- all the analysed features should ideally have been in use at the same point in time. This is however very hard to achieve in most archaeological settings, and many researchers choose to either ignore the issue, or to accept a temporal resolution that is far wider than what their research questions should logically allow for [@perreault2019]. One way of limiting this problem is to select study samples with little to no stratigraphic overlap, which might indicate short occupation span, though as shown below this indicator can also be deceiving. For both study areas selected for this thesis -- the Linear Pottery in south-west Slovakia and the B2/C1 Trypillia of central Ukraine -- settlement plans show very little overlap between houses, even though some of them probably developed over more than three centuries, as shown by radiocarbon dates and modelling (see below). Such settlement plans may be impossible to differentiate into separate coeval time samples without precise dating of construction and abandon of every individual house, counting in the thousands on the Trypillia mega-sites (an alternative method is presented only for the Linear Pottery settlements in Section \@ref(lbk)). On the other hand, the fact that there is so little overlap between houses despite temporal differences clearly illustrates how these settlement plans emerged over time, not as a *tabula rasa* in each generation but rather with new constructions respecting the location and orientation of older ones long after abandonment. Though such practices are indeed interesting, it is not at all obvious, however, to which extent they may reflect or even relate to social factors such as hierarchy. With settlement types with much higher degree of stratigraphic overlap, like the tell sites of the Balkan and Near Eastern Neolithic traditions, it may be easier to distinguish more or less coeval occupation phases, but they are again harder to document extensively -- because of the high density of archaeological finds and features, excavation surfaces typically cover only very small portions of the settlement, while remote sensing performs less well and not allowing for temporal disentanglement of constructed features (\#**citation**). In any case, the issue of temporal resolution of the data and its influence on analytical results is crucial, and will be discussed repeatedly throughout this thesis, with a summary in Chapter \@ref(disc-methods).

Comparative technology

Meaning of "house"

In the following I propose a very brief overview of the general archaeological contexts of the two cases analysed in this thesis, namely the Linear Pottery and the Trypillia cultures. Both have been extensively studied and enjoy long and rich research histories, and any attempt at a comprehensive overview here would be futile. In stead, I focus on the aspects that are the most relevant for the present study -- in particular of architecture, settlement layout and social organisation -- and address the interested readers to more complete reviews. In the final sections of this chapter I provide some discussion on the nature and limits of the data material used here, which consists mainly of geomagnetic imagery with expert interpretation of archaeological features, as well as synthetic data for simulations.

## The Linear Pottery culture complex {#lbk}

General intro to the culture: @bickle2013 (online!); @whittle2014.

Formation, characteristics -- striking difference from earlier Mesolithic cultures, hence the term "Neolithic Revolution" pinned by Vere Gordon Childe for the seemingly abrupt transition to agriculture in continental Europe with what he called the Danubian Ia **ref**. @whittle2022, check with Trigger!

expansion trajectory: east: @saile2020,

Questions of contact and even creolisation with local hunter-gatherer groups in the margins of the Linear Pottery settlement area -- Limbourg and La Hoguette pottery groups in northern France and Belgium, Swifterbandt in the Netherlands??, Ertebølle in northern Germany??, Bug-Dniestr in Ukraine and Moldova [@saile2020] -- as well as with other already established Neolithic groups in central France [@roussot-larroque2022] and the lower Danube [@saile2020], remain hotly debated

End of LBK as collapse? The whole culture as an adaptive cycle: @gronenborn2014.

Organisation of Linear Pottery society: egalitarian or hierarchic? Cemeteries: @jeunesse2022, check @gaydarska2023 and @augereau2021. Linear Pottery architecture and house construction

origin of the longhouse: @bánffy2020, @coudart2015, @last2015

house typology, construction, and use: @modderman1970, @coudart1998

house orientation: "origin" hypothesis: @bradley2001

Number of coeval houses in LBK villages, evaluated to a mean of 5, sd. 3 [@coudart1998, p. 91]. Furthermore, based on ethnographic analogies she estimated a typical Linear Pottery village of 3 to 8 houses (of which 1 or 2 longer than 22 m), to include on average approximately 150-260 inhabitants, though fewer (up to around 80 people) for the smallest hamlets of 3 houses.

Patrilocality in LBK based on Sr isotopes: @hrncir2020a (read this more carefully), and other data (check) @schiesberg2016.

The Žitava valley and research project

### Time samples of the Vráble settlement (moved from Chap. 6, review to check it fits)

Separating an archaeological settlement plan into samples with temporally coeval structures only is a demanding exercise, and more so the larger the settlement. The best and most reliable method is to date every single structure in the settlement, but this is usually impossible both in theory, since not all structures yield datable material, and in practice when considering the costs involved. The more realistic approach is to sample a smaller amount of structures throughout the settlement for dating and modelling, and then extrapolate the results to get a more or less rough overview of how much, proportionally, of the site was occupied at the same time. This has been done for the Trypillia mega-sites, indicating that the maxima of coeval habitation would be at approximately 33% of houses at Nebelivka [@millard2020, pp. 253-6; @muller2022] and 52% at Maidanetske [@ohlrau2020, pp. 233-5; @ohlrau2022, pp. 86-8]. Even though some general tendencies of the spatio-temporal development of these settlement plans have been proposed [@shatilo2021, p. 247; @muller2022, pp. 218-9], it is for now impossible to extract precise temporal samples of coeval house-size distributions here. This also goes for the image analysis presented in Chapter \@ref(images-results) [see also @bruvollforthcoming]. The smaller sites of Moshuriv and Talne 3 are only dated through relative chronology of surface finds and thus attributed as a whole to their chronological phase, though their small sizes and ordered layout would suggest that most houses could be coeval [@ohlrau2020, pp. 241-4].

For houses in Linear Pottery settlements, a special dating proxy was recently developed, based on the observation that within this cultural context houses were constructed to be parallel to pre-existing ones, but with a slow and gradual counter-clockwise shift in orientation of approximately 1.3 degrees per decade [@muller-scheessel2020]. This shift was hypothesised to be too slow for any conscious intention among the house builders, but rather a result of so-called pseudoneglect, or the tendency of a slight leftwards bias in the perception of parallel lines, mostly among the right-handed. @muller-scheessel2020 observed this gradual shift in the orientation of 17 houses in Vráble for which construction dates had been estimated based on Bayesian modelling of ^14^C dates. Their linear regression model for all these houses only gave a weak correlation however, and they argued for basing the model on the eight houses in the SW neighbourhood only, where the sampling strategy had been the most systematic. This gave a regression model defining house orientation as $0.129x - 651.016$ with correlation coefficient $r = 0.84$, $x$ being the modelled construction year BCE, which when applied inversely (solving for $x$) gives modelled construction year as $\frac{orientation + 651.016}{0.129}$. Use-life of houses in Vráble was modelled by @meadows2019 to a median of 27.5 years, a number which according to the same authors has varied greatly throughout the long history of Linear Pottery research. Extrapolating the model for construction year based on house orientation and adding this median duration onto all known houses in Vráble gives a settlement occupation span from 5297 to 4975 cal. BCE, which is in good agreement with the currently available and modelled ^14^C dates [though admittedly a few decades earlier, see @meadows2019]. For the distribution fitting analysis in this section I defined a set of 16 sample dates spaced 20 years apart from 5290 to 4990 within this timespan, and assigned houses to each sample accordingly. Since the duration between time samples is a few years shorter than the duration of houses, some houses were assigned to more than one sample. Furthermore, as with the analyses above, samples with 10 or less houses in them were filtered out, mainly since the distribution method then becomes too unreliable (this is already a quite generous allowance, Chapter \@ref(methods-distfit)), but also since it makes little sense to speak of hierarchy in a group of less than 10.

It must be noted that there are several caveats with this procedure of selecting out houses to be considered coeval. Firstly, the dating proxy method proposed by @muller-scheessel2020 is recent and not yet well established. It is based on linear regression of very few data points (8 houses in only one part of the settlement), all of which are not unique certain values but dates that are themselves also modelled. Though the publication does not specify it explicitly, it seems their model was fitted by ordinary least squares (OLS) regression, while systematic measurement uncertainty in the independent variable (the modelled ^14^C dates) should warrant more robust methods like orthogonal regression or probabilistic Monte Carlo methods. My use of a single value for house duration rather than the probability distribution that it really is, is also a simplification that could affect the results of the analysis. In general, longer house durations lead to more of the houses being coeval throughout the timespan of a settlement, while inversely shorter house durations lead to fewer coeval houses. There could also potentially be systematic relationships between house size and duration, e.g. that larger houses were occupied by more temporally stable households for several generations, putting in greater efforts to maintenance. These questions are not further pursued here however, and the results of this analysis must be considered preliminary.

## The Cucuteni-Trypillia culture complex {#trypillia}

The Cucuteni-Trypillia culture complex (CTCC) is also a large and relatively well-defined archaeological culture, geographically somewhat less extensive than the Linear Pottery, but defined over a longer chronological range of almost 2000 years from the early 5th millennium to around 3000 BCE [@harper2021; @harper2023]. Covering a large area within modern Ukraine, Moldova and Romania from the foothills of the Carpathians in the west to the middle Dnieper in the east -- though inland from the coast of the Black Sea -- it was independently identified in the late 19th centrury at the eponymous sites of Trypillia on the right bank of the Dieper (Kyiv Oblast in Ukraine, then within the Russian Empire) and in Romania at Cucuteni (Iaşi County near the border to Moldova). Over much of the 20th century it has been debated whether they should be considered as two separate cultures, and today they are generally treated as one, or at least as closely related as seen through their highly similar pottery traditions [@shatilo2021, p. 13]. One significant trait that does distinguish Cucuteni and Trypillia settlements, is a tendency of the former to form irregular grid layouts, while the latter form radial layouts of concentric circles. The Trypillia culture is furthermore conventionally differentiated between a Western and an Eastern sub-group, the former (abbreviated to WTC in specialised literature) being primarily characterised by the prevalence of polychrome painted pottery (similar to Cucuteni pottery) while the Eastern group (ETC) is characterised by pottery with primarily incised and fluted decorations. There is also a general long-term trend of migration and pioneer settlement from the south-west towards the north-east, and the ETC -- representing the earliest settled farmers in central Ukraine -- first appear after the initial stages of WTC and Cucuteni development [@harper2023, pp. 646-7]. It should also be noted that both of the eponymous sites are located in the extremities of the area defined by associated sites, and though there are certain geographical biases in the documented material, it seems clear that the core area of settlement and population density for much of the CTCC duration was in and near the river valleys of the Dniestr and Prut (mainly in present-day Moldova and central-western Ukraine). The Trypillia settlements included in this study are attributed to the WTC and are located within a small micro-region in the Southern Bug-Dnieper interfluve, around the limit between the Cherkassy and Kirovograd oblasts, some 30-40 km east of Uman (#overview map).

The near absence of stratified settlements within the Trypillia and the low availability of radiocarbon dating for Soviet and post-Soviet archaeologists, has lead to the elaboration of a highly complex sequence of relative chronology based on pottery typology, with the definition of a number of geographically unstable local traditions, termed "local groups" for both the WTC and the ETC. These are generally thought to represent somewhat coherent population groups, changing the location of their settlements at a relatively rapid rate, often in small steps but from time to time in larger leaps, leading to considerable geographical overlaps and mixing between different traditions (e.g. the WTC settlements presented below are actually further *east* than most of the ETC settlements).

-   Ceramics typology, Local groups and phases.

-   Economy:

    -   Subsistence: agriculture, husbandry, hunting. Forest-steppe eco-zone.

    -   Artisan specialisation in fine ceramics? Metal finds -- gold and copper.

-   House construction and architecture

    -   House typology

    -   Clay models of houses

    -   Burning

-   Social organisation

    -   Lacking burials (but further south?)

    -   Mega-sites as exception

        -   Urban or not? Density and diversification. Comparative

        -   The seasonality hypothesis -- relations to the hinterland

        -   Government system -- assemblies or chiefs/kings?

-   My sample

    -   The German-Ukrainian research team

    -   The British-Ukrainian team

@pickartz2019, pp. 1649-50: "unburnt" and "eroded" are misleading labels, since highly burnt and even vitrified material regularly found during excavation of these. Probably reflecting houses that are constructed with less daub, without an oven installation, and/or without raised clay platform, thus causing significantly weaker magnetic signals. These houses may in fact represent entirely different social functions from regular houses, but there is as for now no consensus as to what this may be (e.g. artisanal, storage etc.)

The B2/C1 and the mega-sites of the Southern Bug -- Dnieper interfluve The urbanism debate: Comparison with Uruk in Müller and CHECK; low-density urbanism for Nebelivka: check for refs. in @ohlrau2022,p .91 cc. Mega-sites as *anomalocivitates*: @ohlrau2022 and @sindbæk2022.

## Reading site plans from geomagnetic imagery

Caveats: fill in here.

@pickartz2021 fds

Say where the shapefiles come from here. @muller-scheessel2020; @hale2020; @ohlrau2020 (double-check in my article)

## Synthetic data

And why I'm not (this time) relying on ethnographic data.

Don't go into technicalities here, just the reasoning.
