# Methods: Distribution fitting {#methods-distfit}

## Heavy-tailed distributions, testing for power laws

-   Technical characteristics of power laws, @newman2005, do I need more?

-   Old style distribution fitting (which is used in @brown2010 and @brown2005 and check. @mitzenmacher2004, @harrison1981

-   New style presented in @clauset2009, @stumpf2012, implemented in R with the poweRlaw package @gillespie2015, and used in @strawinska-zanko2018 and @crabtree2017. More recent?

## Methodological procedure

-   Reminder of main goal for this part of the study: identify power-law structures in the house-size distributions of the Linear Pottery and Trypillia samples.

-   Synthetic data genaration:

    -   Why?

        1.  Process: how long/much does it take for a normal distribution to become power-law? And reverse sense?

        2.  Temporal resolution issue: does the temporal palimpsest of several phases with e.g. log-normal distributions produce false power-law signals?

    -   How?

        -   Random number generation and iterated multiplicative (1.) or additive (2.) sequences, with K-S testing [@gillespie2015] at each stage. Report when the distributions become power laws.

-   Present data set with categories (settlements, quarters/neighbourhoods, time samples for Vráble)

-   Parameter settings: dist. types, xmin, testing the pl hypothesis etc. Minimal house-count cutoff (min. sample size). Isolating top house.

## 

END chapter
