# Results: Distribution fitting {#results-distfit}

## Synthetic distributions

1.  Multiplicative process

A multiplicative process is one in which a term is multiplied with itself a number of times, and can be mathematically described through an exponential function. This is commonly denoted $$f(x) = ab^x$$, read as "the function of *x* equals *a* times *b* to the power of *x*", where *b* is the main term which is multiplied with itself *x* number of times, and *a* being a constant of proportionality. In such functions, *b* determines the *shape* of the function -- if between 0 and 1, the function models exponential decrease or decay as *x* grows larger, and if $b > 1$ the function models exponential growth. This term corresponds to the *rate* parameter for exponential distributions detailed in Section \@ref(distributions). The *a* term determines the *scale* of the function, similarly to the y-intercept of a linear function of the type $f(x) = ax+b$ (in this case *b*), and though in an exponential function this *a* is multiplied rather than added to the variable term (*b^x^*), its value gives the y-intercept since $ab^x = a$ when $x = 0$. Furthermore, the link between exponential and linear functions is illustrated more clearly when we log-transform the former, that is: $f(x) = log(b)x+a$, which is essentially a linear function where *a* is the y-intercept and *b* is the slope (\# Show with fig! and go on).

#Insert figure, ill. exponential functions.

1.  Additive process

Lumping of samples may be done for two main reasons (in archaeology): 1 - the sample size is too small, and lumping together several contemporary samples can raise the sample size to an acceptable level (spatial lumping), or 2 - it is impossible to temporally disentangle elements within a settlement, i.e. reduce temporal resolution to coeval elements, in which case one has no option but temporal lumping (accepting a low temporal resolution). The problem can be further broken down to two case types: a) all lumped samples are really drawn from the same distribution, and b) they are not similarly distributed (**illustrate with table**). For spatial lumping this degree of similarity can be assessed, but not necessarily for temporal lumping. But even when it can be assessed, the lumping needs to be justified in social terms. As an example, several spatial samples (e.g. villages in a region) can have house-size distributions with no significant differences between them (ANOVA), but at the same time be functionally entirely independent, in which case it is more logical to augment the sample size of a single one through simulation and evaluate plausibility through bootstrapping, rather than by lumping of all samples, **rewrite this more clearly**. On the other hand, house sizes can be significantly different between quarters or suburbs within a city or metropolitan area, or even between cities in a region or country, but if they all function together in a coherent system, they may reflect a spatial segregation between different strata in the society, and it makes much sense to lump and analyse them together.

When it comes to temporal lumping, given that a settlement does not undergo substantial cultural changes during its timespan, a workaround to evaluate whether the house-size distribution evolves significantly over time may be to target a number of size categories for ^14^C dating, and to check that they all stretch over the entire range of the settlement's duration, and if yes, accept to analyse the whole distribution as one. **recheck this after I have my results, maybe move it all to summary**.

## Settlements

House-size distributions of whole settlements (both Linear Pottery and Trypillia)

## Quarters/neighbourhoods

House-size distributions of separate quarters (Nebelivka) and neighbourhoods (Vráble). Can I include separate Nebelivka neighbourhoods as well? (prob. too small, but check)

## Temporal samples (Vráble)

If time, I can add more Žitava sites here, but not necessary. I can also analyse temporal samples of Vráble neighbourhoods separately.

## Summary of findings

END Chapter
