# (PART) Settlement Plans {.unnumbered}

# Village planning in prehistory {#images-theory}

Systematic relationship between settlement layout and social structure in small-scale societies has been the topic of some ethnographic studies. In a comparative study of ethnographic examples from all over the world, @fraser1968 showed that some tendencies existed, but that there was also large variation. One trait was that the more mobile the society, the less strict where the overall planning principles, while planning tended to be more organised in more settled, as well as hierarchic societies. Religious, cosmologic and defensive concerns were shown to influence the relative placement of buildings, but not in any uniform way cross-culturally. More recent kinship studies have attempted to link different kinship structures with settlement layouts [@ensor2017a; @ensor2013; @souvatzi2017], but methods for effectively quantifying these layouts and thus allowing for cross-cultural regularities to be apprehended have been largely lacking. Factors that may be hypothesised to affect village layouts in systematic ways include:

-   Political structure (but, as with hierarchy, an organised layout does not necessarily equate top-down despotic decision making, as other strong social institutions may be anarchic or heterarchic)

-   Kinship, matrimonial and locality structures

-   Cosmology (e.g. Linear Pottery house orientations)

-   Economic and ritual functions of village elements (constructed and non-constructed)

-   Local landscape setting (to be factored out)

The maybe most promising results in this direction in prehistoric archaeology have been presented by @furholt2016, who identified two distinct village types in the early Neolithic of the Aegean region, based on layouts observed and coded into a range of quantitative and qualitative variables. Furholt applied correspondence analysis to reduce the dimensionality of his data set, resulting in a rather clear distinction between a compact bee-hive-like "Anatolian village" and a more dispersed "Balkan village", which would become representative of later developments in south-east Europe. He interpreted these layout differences in terms of social organisation, in that the Anatolian type would have tighter and stronger overarching community structures, while the Balkan village showed stronger independence between households.

While intriguing, the assumptions underlying interpretation are difficult to test, from the lack of comparable material, in particular from ethnography. Furthermore, studies like that of @fraser1968 provide settlement plans which by quality and precision generally do not meet the standards and requirements of archaeology, and it is difficult to perform any meaningful quantitative analyses on them.

In this part of the thesis, I wish to contribute to this topic, with the application of fractal image analysis. In particular, I believe that the theory underlying fractal geometry may well translate into social processes involved in the emergence of settlement layouts.

## The geometries of conscious planning vs. emergent behaviour {#layouts}

The rationale of the following analysis is simple: Regular Euclidean patterns -- like rectangular grids, circles and straight lines -- result from conscious planning, while chaotic, irregular fractal patterns are indicative of independent households. This distinction should not be considered as binary, but along a continuum, and it is hypothesised that the degree of planning versus household autonomy can be effectively quantified through fractal analysis [see @bruvoll2023].

As mentioned earlier, fractal geometry was first developed by @mandelbrot1982, who defined certain measures to describe patterns that were too irregular to be quantified through traditional geometry. The main measure he proposed was termed the *fractal dimension*. This was meant as an extension of the Euclidean dimensions (what we refer to when saying 2D or 3D), by taking on fractional values in addition to integer values. A pattern with a fractal dimension of 1.5 would be neither a curve (1D) nor a plane (2D), but something in-between, that is, a broken pattern which does not fill its embedding dimension -- in this case a two-dimensional plane. Such a pattern could be the Sierpinski triangle or the von Koch curves seen in Chapter \@ref(theory), or real world features like coastlines, river systems, Moon craters or national borders.

The fractal dimension was defined by Mandelbrot as

$$
D = \frac{log N}{log 1/r}
$$

where N is element count and r is scale (as fraction of the whole). @mandelbrot1982 effectively applied this measures to a range of mathematically constructed fractals, showing its usefulness as quantification of highly irregular shapes.

He furthermore noted that while this dimension was indicative of the degree of space-filling or completeness of patterns, in many cases patterns with very different image textures could be shown to have the same fractal dimension. As *D* is a summary measure (calculation methods are explained in the next chapter), it does not say everything about the data it describes, similarly to how a mean of a data distribution does not in itself say anything about the spread of the data. For describing the texture of fractal patterns, he tentatively defined *lacunarity*, mathematically expressed as

$$
L = 1 + (\frac{\sigma}{\mu})^2 
$$

or the variance to square mean ratio of foreground pixel mass [see @hingee2019 for an extensive review of the development of lacunarity measures since Mandelbrot]. It quantifies the distribution of voids or gaps in the pattern (*lacuna* being Latin for gap or lake), and has since been included in a variety of studies of texture, however mostly within the natural sciences.

While these measures are held to quantify the regularity or irregularity of spatial patterns, applying them to archaeological settlement plans is not straight-forward. First of all, it is not entirely beyond doubt that fractal settlement plans are always unconsciously emergent [@eglash1999]. Also, it is not obvious how exactly fractal dimension and lacunarity estimates on empirical plans differentiate between Euclidean and fractal patterns. I recently showed that random noise in synthetically generated images was correlated to both *D* and *L*, but there are challenges involved in transferring this to archaeological settlement plans [@bruvoll2023]. The interaction between other texture-related variables and their relative influence on fractal dimension and lacunarity estimates are largely under-studied, seemingly in any discipline (in archaeology these discussions are largely absent, as reviewed below).

The relationship between image density (built-up area) and fractal dimension was evaluated by @thomas2007, who showed that these two parameters, under certain conditions (constant observation window, prefactor values close to 1), are exponentially correlated. They furthermore showed that observation window size and shape, as well as centroid placement, have little influence on *D*, while they have more influence on density when the pattern is not homogeneous. They do show, however, that images with the same density may have quite much variation in *D*, which is reflected in the layouts. Judging from their examples, more clustered layouts give higher *D* values, while more dispersed or dusty layouts give lower *D*, when density is constant. According to @thomas2007, density is a crude measure of the overall intensity of the pattern, while fractal dimension characterises the morphological structure, though it is not directly descriptive. Lacunarity measures were tested on urban patterns by @myint2005, but have not yet become a standard tool in quantitative urban studies.

## Fractal image analysis in archaeology {#image-archaeo}

Intra-site spatial analysis approaches have in general received much attention in archaeology, and analytical methods and techniques specifically related to architecture and spatial organisation are known as space syntax, point-pattern analysis, Ripley's K, visibility graph analysis, viewshed analysis and access analysis, to name a few [see @gillings2020 for a recent comprehensive review]. However, few of these, if any, use complexity theoretical frameworks [the percolation analysis proposed by @maddison2020 is seemingly an exception], and I believe fractal analysis can become a valuable supplement to the panoply of spatial analysis methods, in particular because of its explicit theoretical framework.

In archaeology, seemingly all previous applications of fractal image analysis have been done in Mesoamerican contexts. The earliest example of which I am aware, is a study by Oleschko et al. [-@oleschko2000; commented on by @brown2005] on the Ciudadela complex in Teotihuacán, Mexico, where the measured fractal dimension was reported to be close to that of the mathematical fractal known as the Sierpinski carpet. From this the authors argued that the two may have similar underlying generative mechanisms. @brown2003 adapted the method further to archaeological settlement plan drawings, and compared measurements on different quarters and settlements from classic Maya Yucatán.

The study which contributed the most with impetus for the analysis presented here, was done by Farías-Pelayo [-@farias-pelayo2017; more detailed in -@farias-pelayo2015], who, apparently as the first in archaeology, added lacunarity measures to better apprehend the particular patterns of lithic artefacts, petroglyphs and site topography (not settlement layout) within the Xajay culture in central Mexico. By combining fractal measures of different material series into a single index, she claimed to better characterise this culture which has proven difficult to characterise through traditional typology.

These limited developments are the reasons for the largely exploratory and experimental nature of this part of the thesis, where the methodological discussions provided are probably of as much, if not more interest than the results from the archaeological analysis.
