# Methods: Fractal image analysis {#images-methods}

fdasdf

## Calculating fractal dimension and lacunarity

-   Box-counting, lit. @mancuso2021, @li2009, @klinkenberg1994

-   Gliding-box algorithms, @allain1991, @hingee2019, @cheng1997, @plotnick1996

-   Caveats:

    -   Fractional box-counting dimension does not equal self-similarity in a simple way

    -   My summary *L* is not equal to the one used in *FracLac* and thus by @farías-pelayo2017

-   Image preparation procedure

## Testing on Euclidean and self-similar layouts

fds

## Testing on density, element count and size distribution

Relationship between image density (built-up area) and fractal dimension, evaluated in @thomas2007, where they show that these two parameters, under certain conditions (constant observation window, prefactor values close to 1), are exponentially correlated, which is also what I found in my article. They show that observation window size and shape, as well as centroid placement, have little influence on *D*, while they have more influence on density when the pattern is not homogeneous. They do show, however, that images with the same density may have quite much variation in *D*, which is reflected in the layouts. Judging from their examples, more clustered layouts give higher *D* values, while more dispersed or dusty layouts give lower *D*, when density is constant. I ignore the use of prefactor values. According to @thomas2007, density is a crude measure of the overall intensity of the pattern, while fractal dimension is characterises the morphological structure, though it is not directly descriptive.

## 

## Summary of procedure and tests

-   Procedure for archaeological samples, same as in article

-   Procedure for synthetic sample

END Chapter
