# (PART) Synthesis {.unnumbered}

# Social complexity in Neolithic settlements {#disc-results}

While the primary goal of this thesis has been to study fractal analysis methods themselves and how they can become better integrated into archaeological research, this assessment could hardly be done without reference to how well they account for patterns in real-world data. For the case studies included here -- the sampled Linear Pottery settlements in the Žitava valley, Slovakia, and Trypillia settlements in the Sinyukha basin in Ukraine, which have largely been analysed together -- a number of observations of more culture-historical nature can be made, which can furthermore be interpreted in light of recent research on these culture groups and settlements.

As seen in Chapter \@ref(material), for both the Linear Pottery and Trypillia culture groups there has been much discussion among specialists regarding their social organisation and possible levels of hierarchy. Both archaeological cultures are well defined by a number of characteristics of material culture, and they have been extensively documented for decades. However, recognising specific traits of social organisation in archaeology is a complicated matter, and it is often difficult to evaluate different hypotheses against one another. Also, despite obvious similarities in material culture within large geographical zones -- as is seen in house architecture within the Linear Pottery area -- specific traits of social organisation that are seen in one study area are not necessarily valid for the whole archaeological culture. Broad generalisations may be useful for apprehending complex phenomena, but they also have a tendency to make us blind to evidence of variation. This is a frequently recurring discussion in archaeology, and indeed in most academic disciplines [@graeber2021; @furholt2021a].

Expert opinions on the social organisation, and specifically the degree of hierarchy, have evolved with somewhat different dynamics in Linear Pottery and Trypillia research. For the former, there has been a pattern of oscillation over time between interpretations tending towards strong egalitarianism [e.g. @pavuk1972; @gimbutas1991; @coudart2015] *contra* lineage- or clan-based society dominated by elites with inherited status [@vandevelde1990; @jeunesse1996; @bogaard2012; @bentley2012; @augereau2021], with perhaps the majority of researchers seeking some middle ground [e.g. @last2015; @whittle2014; @hamon2021; @hofmann2017]. The most striking feature of this debate is how the different points of view are forwarded largely from the same material. There seems to be at least a week tendency of science-oriented research concluding with more hierarchy, and humanities-oriented research arguing for less hierarchy or at least more variation. Characteristically, the middle-ground advocates tend to be those who manage to incorporate both approaches in their analyses. In Trypillia research on the other hand, interpretations of social organisation have largely followed national schools of thought. Researchers in British-led projects have stressed the communal nature of large buildings and the lacking material evidence for social elites, arguing for a largely democratic-egalitarian society [@gaydarska2020; @chapman2016]. In German-led projects, interpretations have focussed on temporal dynamics and indications of a gradual shift from communal to elite-led governance, which is claimed to have contributed to the ultimate decline of the mega-site phenomenon [@hofmann2019; @muller2016c]. It should be noted that these two interpretations are not mutually exclusive, as the British-led research has been focussed on Nebelivka, which is one of the earlier mega-sites [@muller2022]. Ukrainian researchers have followed the more culture-historical tradition, constructing detailed typo-chronological sequences with the goal of tracing migratory movements of coherent social groups, largely avoiding hypothesising on their social organisation [@diachenko2012a; @kruts2012; @ryzhov2012].

## Hierarchy in Neolithic house sizes

The distribution-fitting analysis presented in Chapter \@ref(results-distfit) allowed for the identification of power-law distributions in both Trypillia and Linear Pottery house sizes. While house sizes are regularly reported in archaeological settlement studies, this approach has to the best of my knowledge not been applied to settlements in Neolithic Europe before. As seen in the theoretical overview in Section \@ref(distributions), power-law distributions are clear indications of hierarchically scaling structures. The power-law distributions observed in these house-size samples therefore constitute a strong argument for some sort of hierarchy in their interrelations. What exactly this hierarchy consisted of however, is a different matter.

For the Linear Pottery settlements, and apart from the deviating results for Horný Ohaj which was probably due to the small sample size, only the largest settlement of Vráble was interpreted to have power-law distributed house sizes. While the distributions of the smaller settlements were almost always skewed (with the exception of normally distributed Úľany nad Žitavou), they were markedly less so than that of Vráble, and were interpreted as log-normals. The Vráble settlement, with its total of 313 houses is also markedly larger than the other settlements, of which Vlkas is the largest with 61 houses (Table \@ref(tab:06-settle-tab)). It was hypothesised that the result for Vráble was a statistical artefact reflecting arbitrary data aggregation rather than an actual hierarchy. However, further analysis on separate neighbourhoods and time samples revealed hierarchical scaling also there, including for sub-samples with less than 20 houses, indicating that the observed difference in house-size distributions between Vráble and the other settlements was a robust result.

Temporal modelling was not done here for the smaller sites, but following [@muller-scheessel2020; see also @furholt2020a] it can be assumed that not all houses were coeval there either, but rather that they also developed dynamically over time. If there was a threshold of village population size above which Linear Pottery households would begin to organise hierarchically (Chapter \@ref(theory)), it is likely that it would be found already at a low number of coeval houses -- possibly around a dozen. There is currently not enough evidence here to estimate such a threshold with any precision, both because of the very limited geographical scope of this study, but also since this number is also where the distribution-fitting algorithm applied here becomes unreliable. It is also very difficult to attach such a threshold in number of coeval houses to any absolute population estimate, as these vary widely between authors for the Linear Pottery culture. As mentioned earlier, @coudart1998 estimated the typical Liner Pottery hamlet to consist of about five coeval longhouses with a total population of 150-200 (amusingly close to Dunbar's infamous number). Coeval house numbers for the temporal samples of Vráble are much higher, roughly in the range of 20-60 houses, and even when considered separately, temporally coeval social groups within single neighbourhoods could in many phases reach twice or three times as high populations, i.e. totals of 300-600 people, if we accept her estimation methods (Table \@ref(tab:06-time-tab)). It could be argued that whenever Linear Pottery social groups grew beyond about 200 inhabitants -- which was evidently rare given that the vast majority of known settlements were indeed smaller -- a possibility emerged for clan leaders to take on a distributive role and actively seek to increase their political and economical dominance over other households. In a settlement like Vráble, where the whole was clearly sub-divided in three distinct neighbourhoods, competing interests between such clan leaders could over time lead to significant tensions. This can again be discerned in the construction of the enclosure and the associated human remains surrounding the south-west neighbourhood dated to its later stage of development [@furholt2020b; @muller-scheessel2021].

While admittedly speculative, this interpretation is corroborated by evidence from Linear Pottery cemeteries indicative of higher social status for local-men-with-adzes [@bentley2012; @whittle2013a] and their probable link to the largest houses [@vandevelde1990]. Furthermore, the argument presented by @jeunesse2022 regarding differences between generally "rich" and "poor" cemeteries, could be seen as reflective of the difference between villages that have and have not passed the critical point of emerging social hierarchy. This point does not depend on the accuracy or even the relevance of Dunbar's number, which has been much criticised (Chapter \@ref(theory)), but on the observation that larger settlements have power-law distributed house sizes while smaller settlements do not. Testing this hypothesis on wider samples should be a priority for future research.

The link between settlement size and hierarchically scaling house sizes was also seen in the analysed Trypillia settlements. The clearly hierarchical relationship between building sizes at the mega-sites is hard to miss, and has already been recognised by the researchers who have studied them in recent years [@hofmann2019; @chapman2016]. However, the distribution-fitting analysis allowed for a more detailed appreciation of just how far down the scale this hierarchy appears to have gone. While @hofmann2019 acknowledge that some large houses located at entrance points and street corners may have had special functions even though they have not been previously classified as typical "mega-structures", the results presented in Chapter \@ref(results-distfit) indicate that as much as 44% of houses at Nebelivka have sizes distributed in a way that is best described as a power law. Furthermore, mapping where these houses are located in the settlement reveals a strong tendency of concentrations of larger houses near mega-structures and in the main streets, while smaller houses are located more often in side streets and near the borders between quarters (Figure \@ref(fig:06-nebelivka-map)). Though interpretations of the largest structure at Nebelivka have been somewhat inconsistent [@burdo2016; @chapman2016], the public rather than domestic function of at least the medium-sized mega-structures/assembly houses seems well established [@hofmann2019]. As it has been repeatedly stated throughout this thesis, there is no inherent contradiction between hierarchical structures and communal social organisation, and fully egalitarian democracies can very well solve a number of organisational issues through hierarchical scaling of institutions. In contemporary democratic states, this sort of hierarchy often translates to law-regulated bureaucracies [@delanda2006], and can be recognised materially through a number of communally organised networks of public and institutional buildings, as well as infrastructure, which will -- at least in theory -- tend to follow power-law size distributions on various levels [@batty2005; @themath2019]. There is thus no need to explain away this hierarchy simply because Trypillia settlements are thought to be egalitarian. However, these large houses which are centrally placed within the neighbourhoods at Nebelivka have received far less systematic attention in later years than the mega-structures, and there has been an overall consensus that Trypillia domestic houses were constructed with extreme conformity [e.g. @chernovol2012]. At the same time, as reviewed by @hofmann2019, in most cases the supposed public buildings could not possibly fit but a fraction of the use-groups they would represent, meaning that some sort of delegation of tasks must have taken place. It would seem Trypillia household research would draw benefit from the active search for variability that has characterised Linear Pottery research for a long time, as such an approach could potentially nuance the currently dominant view of Trypillia households as strictly egalitarian.

The results for Maidanetske were somewhat less conclusive. The observed power-law distribution of house sizes covered "only" 13% of the total house count (which still represents 300 houses). Several differences both in data quality and settlement characteristics could explain this: The largest building structure is missing from the documentation, but is thought to have been there originally judging from the overall layout. There is more missing data than in Nebelivka -- as the south-east part of the settlement was not included in the distribution analysis because of poorer data resolution. But probably most importantly, it is increasingly being recognised that Nebelivka had a much shorter occupation span than Maidanetske, both being situated in the extremes of the more standard duration of mega-sites [@muller2022]. At the same time, it remains at this stage impossible to reconstruct coeval settlement plans of Maidanetske at single time samples, because of the enormous size of the settlement and the colossal effort that would be needed to date enough houses independently. Given the distortions that was shown to result from arbitrary data aggregation using the method applied here (Chapter \@ref(methods-distfit)), it is likely that the results from Nebelivka are the most reliable in this context.

Interestingly, a power-law distribution of house sizes was also recognised at the much smaller settlement of Moshuriv (84 houses) but not at the smallest Talne 3 (19 houses). As with the results for the Linear Pottery settlements, this could again be an indication that hierarchical scaling between households somehow kicks off above a certain threshold. The fact that this was seen for both the Linear Pottery and the Trypillia settlements, and given the diverging views on their modes of social organisation, would lend support to the interpretation of a mechanism which is not primarily culturally contingent. What would need further cultural explanation, is how some settlements came to surpass the threshold to structural hierarchy while others did not. It should be kept in mind that the sizes of the mega-sites as well as Vráble are highly unusual within their cultural contexts.

## Settlement layouts and scaling

The results from the image analysis approach were overall less conclusive, and more work remains before it can be effectively implemented in archaeological research. However, also there the resulting fractal dimension and lacunarity values outlined a grouping of the settlements which cross-cut cultural attribution. The obtained values seemingly quantified the level of clustering, hierarchical or not, so that the settlements with high *D* and low *L* values were homogeneously compact in contrast to heterogeneously clustered settlements (Figure \@ref(fig:09-settlements)). Interestingly, this partition also cross-cut size categories and distribution models, generating the impression of a highly complex relation to clustering which is seemingly unrelated to these other variables. The method did not deliver as expected regarding the quantification of the level of overall planning (spatial regularity vs. noise). However, it is possible that the sampled settlements were in reality too similar for this effect to become discernible, and the procedure would merit to be tested on much larger and more varied samples. There are highly diverging opinions as to just how regular both Linear Pottery and Trypillia settlement plans really are, and a tool for quantifying this aspect reproducibly would be welcome. The approach with the best performance for this purpose is for now the multivariate correspondence analysis approach, as proposed by @furholt2016.

Though it was not part of this project, a settlement scaling approach seems to be both possible and warranted for Linear Pottery and Trypillia regional analyses. In the current framework as proposed by @lobo2020, @bettencourt2021 and others, it does not appear to have been applied yet to prehistoric Europe [the closest to my knowledge being the analysis of Irish Bronze Age stone circles proposed by @grove2011]. Traditional rank-size distributions for the Trypillia sites in the Sinyukha basin have recently been provided by Shatilo [-@shatilo2021, pp. 218-22], showing rather clearly that they do not follow power laws in any phases (though she words it differently). This indicates that there was no settlement hierarchy for which the mega-sites functioned as central places, but rather that they appeared through an agglomeration process, draining populations from the wider area of smaller communities as well as with influx from migrations from the south-west, as has also been suggested by others [@diachenko2012; @diachenko2015]. While the rank-size analysis in this case seems to work well, a more formal and theoretically sound settlement scaling approach would provide more convincing results. Settlement hierarchies have for some time and increasingly been suggested for Linear Pottery micro-regions (see Section \@ref(lbk)), but usually with qualitative assessment only. Applying settlement scaling analysis on Linear Pottery contexts at different geographical scales could shed more light on the processes involved in the initial spread of agriculture in these regions and the subsequent possible emergence of social elites.
