# Fractal Analysis and Archaeological data {#disc-methods}

## The distribution fitting approach

A number of observations can be made regarding the results obtained from the analyses on synthetic data distributions presented in Chapter \@ref(methods-distfit) and their implications to empirical analyses.

It is widely recognised that confidently differentiating between log-normal and power-law distributions is a complicated matter [@clauset2009; @stumpf2012], and confusions between the two have a deep history in statistical research [@sheridan2018; @mitzenmacher2004; @harrison1981; @gibrat1930]. The question raised by @stumpf2012, of whether it really matters in the end, is intriguing. The generative mechanisms underlying these two heavy-tailed distributions are in many ways similar, but not identical. And only the power law is considered to quantify actual hierarchical/fractal structures, which is the focus of this thesis. However, it is also recognised that strict power laws are extremely rare in nature and society (if they even exist at all) since they involve infinite variance, while most of the phenomena that we are interested in are known to exist within clearly limited bounds. As presented in Chapter \@ref(fig:04-hierarchy), several statistical workarounds have been proposed as solutions to this problem, with composite distributions like the power law with exponential cut-off, or the parabolic fractal distribution. In that case -- and given that the log-normal and the power law are reportedly so difficult to distinguish -- why cannot the log-normal distribution also function as a step-in to account for finite effects?

I believe it is a matter of convenience: the log-normal distribution is so malleable that it can effectively mimic any level of tailedness and asymmetry (kurtosis and skewness in statistical terms) from a perfectly symmetrical normal distribution to an extremely unequally distributed power law. This property makes the log-normal very useful for many purposes, but it also makes it more difficult to distinguish between qualitatively different underlying mechanisms. If the goal is -- like in this case -- to identify a critical point where a system changes its behaviour, like when an undifferentiated social group begins to organise hierarchically, it is not very helpful to model its expressions as a log-normal. Identifying or excluding a power law is more indicative, since it says more clearly if there is or is not a hierarchical structure at hand.

In the results of the empirical analyses presented in Chapter \@ref(results-distfit), the seemingly most characteristic difference between power-law and non-power-law tails (log-normal distributions) for settlements, was the proportion of the distribution included in the tail (Table \@ref(tab:06-settle-tab)). Tails that were interpreted as power laws consisted of a maximum of 44% of the data (at Nebelivka, and excluding Horný which was too small for confident results). Log-normal distributions without power-law tails on the other hand (interpreted as exponentials) had a minimum of 66% and up to 93% of the data in them. All tail $x_{min}$ values were set at the point where they gave the best possible power-law fit. This may indicate that the distinction *is* meaningful after all.

Furthermore, the power laws identified for whole settlements were largely persistent when the distributions were subdivided into separate quarters, neighbourhoods and time samples, as already discussed in the previous chapter. Tests on synthetic data series indicated that aggregated data series (settlement data with low temporal resolution) would not generate false positive power-law distributions, as long as the data aggregation did not involve stacking of essentially differently distributed sub-sets, i.e. different settlements or phases with marked shifts in material culture. Also, small sample sizes were shown to increase the risk of false positive power laws, while large sample sizes reduced the risk. Only the small settlement of Horný Ohaj seems to have given a false positive power-law tail, the other ones being the largest settlements in the sample. Together, these arguments further indicate that the settlements with identified power-law tails were indeed different from the rest, and that this difference was linked to settlement size.

The results from the distribution fitting approach were overall very convincing -- the underlying theory is relatively sound and has great explanatory power, and the methods seem to be reliable also when applied to archaeological data. Interesting culture-historical conclusions were presented in the previous chapter. Future research could focus on extending this application to data sets of poorer quality. In this study, the analysed settlements were sampled primarily based on their extensive documentation and completeness. In most archaeological settings, settlements are not documented in their entire extent, but are "cropped" by a limited observation window, or subject to erosion, or with more complex stratigraphy. Also, as briefly discussed already, the closely related approach labelled Settlement Scaling should be more broadly applied to prehistoric settlement systems.

## The image analysis approach

Fractal analysis of synthetically generated image series with incremental changes in single variables, presented in Chapter \@ref(images-methods), resulted in some critical observations. The three tested variables which were considered to capture essential features of settlement layouts, namely hierarchical clustering, size distribution of pattern elements and random noise, all showed clear correlations both with fractal dimension and lacunarity, even though these tests were not large enough for formal statistical modelling. The first image in each series (which was identical for all three), represented an entirely regular grid, emulating a highly rigid, strictly planned settlement layout. As clustering, noise or size variability were added, fractal dimension decreased while lacunarity increased, at more or less the same rate for all three series.

I believe this to be the most important finding of this thesis: fractal image analysis does quantify deviations from geometrically regular spatial patterns, and can -- for now in theory only -- be used as a proxy for degree of settlement planning versus household autonomy.

However, a number of caveats were also made apparent, which together impeded the production of useful empirical results in this occasion. Firstly, variations in image density was shown to have a much greater effect both on fractal dimension and lacunarity than any of the targeted variables (Figure \@ref(fig:08-all-im)), meaning that a slight change in density could potentially preclude any meaningful insights related to the other variables, if results were to be taken at face value [@thomas2007]. The settlement images analysed in Chapter \@ref(images-results) admittedly all had densities within comparable ranges, but it should be expected that if this analysis also was to include settlement types of much higher densities -- like the early Neolithic "Anatolian village" type discussed by @furholt2016 -- these would show markedly higher fractal dimension and lower lacunarity estimates. Any interpretation in terms of regularity of spatial layout of such results would be flawed, since they would rather simply reflect the differences in settlement density which would drown the signal from the targeted effects.

The strong effect from image density was seen in the diverging results between the time sample images of the Vráble plan and the remainder of empirical settlement plans (Figure \@ref(fig:09-all)). The temporal samples constituted the only one of the image series where density was markedly different from the other (much lower density values), and this was reflected in the results with a clear partition between this series and the others in the scatter plot of fractal dimension and lacunarity. A rudimentary attempt was made to model away the effects from density on *D* and *L* results from the empirical images, which left apparently random *D* residuals, while *L* (the mean lacunarity was used) residuals were largely unaffected. This was not a formal analysis for many reasons, but the results still point in some directions:

-   For fractal dimension, no clear pattern could be discerned that could not be reduced to image density. This could be explained either as the analysed images being too similar for any meaningful patterns to be detected, or that other factors (image size, resolution, edge effects) could prevent these patterns from being detected.

-   For lacunarity, the observed patterns were minimally affected by modelling out effects from density. Since it was shown that the two variables strongly correlated, the fact that lacunarity still could not be reduced to density indicates that the two are also inherently connected beyond a simple correlation. Lacunarity quantifies the regularity (the size distribution) of gaps in a pattern -- it depends on the presence and quantity of gaps and thus on density. On the other hand, lacunarity did prove to quantify textures independently of density. Only larger and more systematic studies could allow for further understanding of how these effects can be made more clear.

From this, it could be tentatively concluded that lacunarity would be more useful for the purpose intended here, than fractal dimension. Another result of this analysis was that the even though the absolute value ranges differ between the two summary statistics of lacunarity reported here -- exponent and mean lacunarity -- the distribution of results were to a great extent equivalent, and any one of them can be used, as long as it is clear which one it is. I have elsewhere shown that prefactor lacunarity also is very strongly correlated to mean lacunarity, to the extent that their measured effects are nearly indistinguishable [@bruvoll2023]. However, since the absolute value ranges between these summary statistics differ, it is important to report which one is being used to allow for comparisons between studies [@farias-pelayo2017; @farias-pelayo2015].

Another problematic side of using fractal dimension and/or lacunarity as proxies for village planning, is that the different texture-related variables which were shown to have similar effects do not translate into social processes in a uniform way. Random noise -- here obtained by letting houses perform random walks -- clearly illustrates non-adherence to overall rules and planning. A settlement plan where every household constructs wherever they like without any concern to the placement of other houses, would resemble white noise. Unequal size distributions on the other hand, are illustrative of hierarchy, as seen in the chapters devoted to distribution fitting. Higher levels of hierarchy would be expected to lead to more detailed settlement planning, maybe even more so in democratic political systems than in autocratic ones. Hierarchical clustering is also, clearly, hierarchical. However, its social implications are not necessarily straightforward.

In their early paper pioneering the use of these methods in the study of archaeological settlements, @brown2003 made the case that hierarchical clustering -- "clusters of clusters of clusters" -- were indicative of nested levels of social cohesion in classical Maya society, from family units, lineages and clans, to larger sodalities and ultimately the city state at the highest level. However, they interpreted this simply from obtaining a fractional dimension value (rather than an integer) from box-counting of the settlement plan, which at this point should be easily recognised as a hasty conclusion. Similarly, @oleschko2000 compared the Ciudadela complex in Teotihuacán with the mathematical fractal known as the Sierpinski carpet, simply from the close fractal dimension result they obtained (at $D \approx 1.89$). The input images they used for the analysis were seemingly black-and-white aerial and satellite photographs, dominated by shadows, vegetation, tracks and other unrelated surface features. While using remote sensing imagery (including geomagnetic) directly in fractal analysis of archaeological features would be an intriguing and potentially rewarding exercise, it seems at the current stage that the method is far from ready to be used uncritically. One possible avenue that seems to become ever more realistic, is using machine learning and artificial intelligence techniques for automating the recognition of architectural features from remote sensing imagery, to then be subject to analysis [see e.g. @guyot2021; @olivier2021]. Though we should not expect machines to do the critical thinking for us any time soon, they could probably take over the laborious task of finding and redrawing features of interest (which would of course need control checks), thus speeding up such studies considerably, and opening up the possibility of performing analyses on drastically larger data sets.
